---
apiVersion: v1
kind: Secret
metadata:
  name: jalapeno
data:
  .username: cm9vdA==
  .password: amFsYXBlbm8=
---
apiVersion: apps/v1
kind: Deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: topology
  template:
    metadata:
      labels:
        app: topology
    spec:
      containers:
        - args:
            - --mock-database
            - "false"
            - --v
            - "5"
            - --message-server
            - "kafka:9092"
            - --database-server
            - "http://arangodb:28529"
            - --database-name
            - "jalapeno"
            # To override ArangoDB credentials extracted from the pod mounted secret,
            # use the following command line parameters.
            #            - --database-user
            #            - ""
            #            - --database-pass
            #            - ""
            - --notify-event
            - "true"
          image: docker.io/sbezverk/topology:debug
          imagePullPolicy: Always
          name: topology
          ports:
            - containerPort: 56769
              protocol: TCP
              name: stats
            - containerPort: 56768
              protocol: TCP
              name: perf
          volumeMounts:
            - name: credentials
              mountPath: /credentials
      volumes:
        - name: credentials
          secret:
            secretName: jalapeno
metadata:
  name: topology
  namespace: default
